---
kind: pipeline
name: linux_aarch64_ctng_cpu_archaarch64c_h4e0283edb0

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_ctng_cpu_archaarch64ctng_target_platformlinux-aarch64ctng_vendorconda_cos7
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_ctng_cpu_archpowerpc6_hea9b17d435

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_ctng_cpu_archpowerpc64lectng_target_platformlinux-ppc64lectng_vendorconda_cos7
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

---
kind: pipeline
name: linux_aarch64_ctng_cpu_archx86_64ct_h764b25bf0e

platform:
  os: linux
  arch: arm64

steps:
- name: Install and build
  image: quay.io/condaforge/linux-anvil-aarch64
  environment:
    CONFIG: linux_aarch64_ctng_cpu_archx86_64ctng_target_platformlinux-64ctng_vendorconda_cos6
    UPLOAD_PACKAGES: True
    PLATFORM: linux-aarch64
    BINSTAR_TOKEN:
      from_secret: BINSTAR_TOKEN
    FEEDSTOCK_TOKEN:
      from_secret: FEEDSTOCK_TOKEN
    STAGING_BINSTAR_TOKEN:
      from_secret: STAGING_BINSTAR_TOKEN
  commands:
    - export FEEDSTOCK_ROOT="$DRONE_WORKSPACE"
    - export RECIPE_ROOT="$FEEDSTOCK_ROOT/recipe"
    - export CI=drone
    - export GIT_BRANCH="$DRONE_BRANCH"
    - export FEEDSTOCK_NAME=$(basename ${DRONE_REPO_NAME})
    - sed -i '$ichown -R conda:conda "$FEEDSTOCK_ROOT"' /opt/docker/bin/entrypoint
    - /opt/docker/bin/entrypoint $FEEDSTOCK_ROOT/.scripts/build_steps.sh
    - echo "Done building"

